PLEASE REFER TO APPENDIX ON HOW TO RUN THE CODE, CHANGE THE FILE NAMES ACCORDINGLY IN ORDER FOR THE DATASETS TO BE IMPORTED ON YOUR SYSTEM. YOU CAN LOCATE THE WHEREABOUTS OF THE CSV'S BY CHECKING THE PATHWAY WHERE THE CODE IS TRYING TO IMPORT

USE localized_url function if there's an error with the imports

In [ ]:
import os
def localized_url(url):

    current_dir = os.getcwd().split("statistical-analysis-and-modeling-of-football-data")[0] + "statistical-analysis-and-modeling-of-football-data"
    branch = url.split("statistical-analysis-and-modeling-of-football-data")[1]
    return current_dir + branch

In [121]:
import numpy as np
import pandas as pd

In [ ]:
sofa_df = pd.read_csv("Data/stats_epl1524_processed.csv")
sofa_indexes_df= pd.read_csv("Data/indexes_1524.csv")
understat_df= pd.read_csv(localized_url("/Users/yarkin/Desktop/Dissertation/statistical-analysis-and-modeling-of-football-data/Understat/Data/understat_match_1524.csv"))

In [123]:
sofa_df.columns

Index(['Corner kicks_home', 'Fouls_home', 'Shots off target_home',
       'Throw-ins_home', 'Ground duels_home', 'Aerial duels_home',
       'Corner kicks_away', 'Fouls_away', 'Shots off target_away',
       'Throw-ins_away', 'id', 'Blocked per shots on target_home',
       'Blocked per shots on target_away',
       'Shots on target per total shots_home',
       'Shots on target per total shots_away',
       'Hit woodwork per total shots_home',
       'Hit woodwork per total shots_away',
       'Shots outside box per total shots_home',
       'Shots outside box per total shots_away', 'Game dominance_home',
       'Game dominance_away', 'Overall game dominance', 'Big chances_home',
       'Big chances_away', 'Fouled in final third_away',
       'Fouled in final third_home', 'Long balls_away', 'Tackles won_home',
       'Crosses_away', 'Dribbles_away', 'Tackles won_away', 'Dribbles_home',
       'Crosses_home', 'Long balls_home', 'Yellow cards_home',
       'Yellow cards_away', 'Offsides_away', 'Offsides_home',
       'Goalkeeper saves_away', 'Goalkeeper saves_home'],
      dtype='object')

In [124]:
sofa_indexes_df

,date,id,home_team,away_team,home_score,away_score,season
0,2016-04-30 16:30:00,6768365,Arsenal,Norwich City,1,0,15/16
1,2016-05-01 11:00:00,6768337,Swansea City,Liverpool,3,1,15/16
2,2016-05-01 13:05:00,6768390,Manchester United,Leicester City,1,1,15/16
3,2016-05-01 15:30:00,6768392,Southampton,Manchester City,4,2,15/16
4,2016-05-02 19:00:00,6768354,Chelsea,Tottenham Hotspur,2,2,15/16
...,...,...,...,...,...,...,...
3415,2023-08-19 19:00:00,11352389,Manchester City,Newcastle United,1,0,23/24
3416,2023-08-20 13:00:00,11352337,Aston Villa,Everton,4,0,23/24
3417,2023-08-20 15:30:00,11352418,West Ham United,Chelsea,3,1,23/24
3418,2023-08-21 19:00:00,11352346,Crystal Palace,Arsenal,0,1,23/24
3419,2023-08-25 19:00:00,11352484,Chelsea,Luton Town,3,0,23/24

In [125]:
sofa_indexes_df.rename(columns={'id': 'sofa_id', 'home_team': 'team_h', 'away_team': 'team_a'}, inplace=True)

In [126]:
sofa_df.rename(columns={'id': 'sofa_id', 'home_team': 'team_h', 'away_team': 'team_a'}, inplace=True)

In [127]:
understat_df.columns

Index(['id', 'fid', 'h', 'a', 'date', 'league_id', 'season', 'h_goals',
       'a_goals', 'team_h', 'team_a', 'h_xg', 'a_xg', 'h_w', 'h_d', 'h_l',
       'league', 'h_shot', 'a_shot', 'h_shotOnTarget', 'a_shotOnTarget',
       'h_deep', 'a_deep', 'a_ppda', 'h_ppda'],
      dtype='object')

In [128]:
understat_indexes_df= understat_df[['id', 'date', 'team_h', 'team_a']]

In [129]:
understat_indexes_df

         id                 date             team_h                   team_a
0        81  2015-08-08 15:45:00  Manchester United                Tottenham
1        82  2015-08-08 18:00:00        Bournemouth              Aston Villa
2        83  2015-08-08 18:00:00            Everton                  Watford
3        84  2015-08-08 18:00:00          Leicester               Sunderland
4        85  2015-08-08 18:00:00            Norwich           Crystal Palace
...     ...                  ...                ...                      ...
3415  22270  2024-05-19 15:00:00     Crystal Palace              Aston Villa
3416  22271  2024-05-19 15:00:00          Liverpool  Wolverhampton Wanderers
3417  22272  2024-05-19 15:00:00              Luton                   Fulham
3418  22273  2024-05-19 15:00:00    Manchester City                 West Ham
3419  22274  2024-05-19 15:00:00   Sheffield United                Tottenham

[3420 rows x 4 columns]

In [130]:
# Check if team_h names match home_team names in sofa_indexes_df
# Show which teams are not matching
# Show for both sofa and understat indexes
def check_team_names(s, u):
    s_teams = set(s['team_h'].unique())
    u_teams = set(u['team_h'].unique())
    return s_teams - u_teams
sofa_team_names = sofa_indexes_df[['team_h']].drop_duplicates()
understat_team_names = understat_indexes_df[['team_h']].drop_duplicates()
non_matching_teams_sofa = check_team_names(sofa_team_names, understat_team_names)
non_matching_teams_understat = check_team_names(understat_team_names, sofa_team_names)
if non_matching_teams_sofa:
    print("Non-matching teams found in Sofa:", non_matching_teams_sofa)
if non_matching_teams_understat:
    print("Non-matching teams found in Understat:", non_matching_teams_understat)

Non-matching teams found in Sofa: {'Hull City', 'Wolverhampton', 'Cardiff City', 'Stoke City', 'Tottenham Hotspur', 'Norwich City', 'Huddersfield Town', 'Leicester City', 'Brighton & Hove Albion', 'Swansea City', 'Leeds United', 'Luton Town', 'West Ham United'}
Non-matching teams found in Understat: {'Hull', 'Tottenham', 'Luton', 'West Ham', 'Leeds', 'Cardiff', 'Leicester', 'Brighton', 'Swansea', 'Norwich', 'Huddersfield', 'Stoke', 'Wolverhampton Wanderers'}

In [131]:
#Non-matching teams found in Sofa: 
# {'Huddersfield Town', 'Hull City', 'Cardiff City', 'Tottenham Hotspur', 'West Ham United', 'Norwich City', 
# 'Leeds United', 'Brighton & Hove Albion', 'Stoke City', 'Luton Town', 'Wolverhampton', 'Leicester City', 'Swansea City'}

#Non-matching teams found in Understat: 
# {'Stoke', 'Leeds', 'Luton', 'Wolverhampton Wanderers', 'Cardiff', 'Norwich', 'Brighton', 'Swansea', 'West Ham', 
# 'Hull', 'Huddersfield', 'Leicester', 'Tottenham'}

# Change Sofa names to match Understat names
def change_team_names(df, replacements):
    df['team_h'] = df['team_h'].replace(replacements)
    df['team_a'] = df['team_a'].replace(replacements)
    return df
replacements = {
    'Huddersfield Town': 'Huddersfield',
    'Hull City': 'Hull',
    'Cardiff City': 'Cardiff',
    'Tottenham Hotspur': 'Tottenham',
    'West Ham United': 'West Ham',
    'Norwich City': 'Norwich',
    'Leeds United': 'Leeds',
    'Brighton & Hove Albion': 'Brighton',
    'Stoke City': 'Stoke',
    'Luton Town': 'Luton',
    'Wolverhampton': 'Wolverhampton Wanderers',
    'Leicester City': 'Leicester',
    'Swansea City': 'Swansea'
}
sofa_indexes_df = change_team_names(sofa_indexes_df, replacements)
# Check again if team_h names match home_team names in sofa_indexes_df
non_matching_teams_sofa = check_team_names(sofa_indexes_df[['team_h']].drop_duplicates(), understat_team_names)
if non_matching_teams_sofa:
    print("Non-matching teams found in Sofa after replacement:", non_matching_teams_sofa)
# Merge the two dataframes on the team_h and team_a columns

In [132]:
sofa_indexes_df

,date,sofa_id,team_h,team_a,home_score,away_score,season
0,2016-04-30 16:30:00,6768365,Arsenal,Norwich,1,0,15/16
1,2016-05-01 11:00:00,6768337,Swansea,Liverpool,3,1,15/16
2,2016-05-01 13:05:00,6768390,Manchester United,Leicester,1,1,15/16
3,2016-05-01 15:30:00,6768392,Southampton,Manchester City,4,2,15/16
4,2016-05-02 19:00:00,6768354,Chelsea,Tottenham,2,2,15/16
...,...,...,...,...,...,...,...
3415,2023-08-19 19:00:00,11352389,Manchester City,Newcastle United,1,0,23/24
3416,2023-08-20 13:00:00,11352337,Aston Villa,Everton,4,0,23/24
3417,2023-08-20 15:30:00,11352418,West Ham,Chelsea,3,1,23/24
3418,2023-08-21 19:00:00,11352346,Crystal Palace,Arsenal,0,1,23/24
3419,2023-08-25 19:00:00,11352484,Chelsea,Luton,3,0,23/24

In [133]:
understat_indexes_df

         id                 date             team_h                   team_a
0        81  2015-08-08 15:45:00  Manchester United                Tottenham
1        82  2015-08-08 18:00:00        Bournemouth              Aston Villa
2        83  2015-08-08 18:00:00            Everton                  Watford
3        84  2015-08-08 18:00:00          Leicester               Sunderland
4        85  2015-08-08 18:00:00            Norwich           Crystal Palace
...     ...                  ...                ...                      ...
3415  22270  2024-05-19 15:00:00     Crystal Palace              Aston Villa
3416  22271  2024-05-19 15:00:00          Liverpool  Wolverhampton Wanderers
3417  22272  2024-05-19 15:00:00              Luton                   Fulham
3418  22273  2024-05-19 15:00:00    Manchester City                 West Ham
3419  22274  2024-05-19 15:00:00   Sheffield United                Tottenham

[3420 rows x 4 columns]

In [134]:
sofa_indexes_df[sofa_indexes_df['team_h'] == 'Manchester United'].sort_values(by='date')

,date,sofa_id,team_h,team_a,home_score,away_score,season
350,2015-08-08 11:45:00,6767929,Manchester United,Tottenham,1,0,15/16
370,2015-08-22 11:45:00,6767960,Manchester United,Newcastle United,0,0,15/16
336,2015-09-12 16:30:00,6768041,Manchester United,Liverpool,3,1,15/16
296,2015-09-26 14:00:00,6768081,Manchester United,Sunderland,3,0,15/16
268,2015-10-25 14:05:00,6768101,Manchester United,Manchester City,0,0,15/16
...,...,...,...,...,...,...,...
3120,2024-04-07 14:30:00,11352374,Manchester United,Liverpool,2,2,23/24
3083,2024-04-24 19:00:00,12190336,Manchester United,Sheffield United,4,2,23/24
3090,2024-04-27 14:00:00,11352463,Manchester United,Burnley,1,1,23/24
3055,2024-05-12 15:30:00,11352532,Manchester United,Arsenal,0,1,23/24
3059,2024-05-15 19:00:00,12240571,Manchester United,Newcastle United,3,2,23/24

In [135]:
sofa_indexes_df.loc[:, "year_month"]= pd.to_datetime(sofa_indexes_df['date']).dt.to_period('M')
understat_indexes_df.loc[:, "year_month"]= pd.to_datetime(understat_indexes_df['date']).dt.to_period('M')

/var/folders/3p/hrcdb8192mbby6r18mgdgb2c0000gn/T/ipykernel_98990/1171144297.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  understat_indexes_df.loc[:, "year_month"]= pd.to_datetime(understat_indexes_df['date']).dt.to_period('M')

In [136]:
sofa_indexes_df.loc[
    (sofa_indexes_df["team_h"] == "Stoke") & 
    (sofa_indexes_df["team_a"] == "Swansea") & 
    (sofa_indexes_df["year_month"] == "2016-10"), 
    "year_month"
] = "2016-11"

In [137]:
merged_indexes_df = pd.merge(understat_indexes_df, sofa_indexes_df, on=['team_h', 'team_a', "year_month"], how='left')

In [138]:
merged_indexes_df[merged_indexes_df["id"]==2686]

,id,date_x,team_h,team_a,year_month,date_y,sofa_id,home_score,away_score,season
479,2686,2016-11-01 00:00:00,Stoke,Swansea,2016-11,2016-10-31 20:00:00,7090118,3,1,16/17

In [139]:
df_to_save = pd.merge(merged_indexes_df[["id", "sofa_id", "year_month"]], sofa_df, on='sofa_id', how='left')

In [140]:
df_to_save = pd.merge(df_to_save, understat_df[["id","team_h","team_a","date", "h", "a"]], on='id', how='left')

In [141]:
df_to_save

,id,sofa_id,year_month,Corner kicks_home,Fouls_home,Shots off target_home,Throw-ins_home,Ground duels_home,Aerial duels_home,Corner kicks_away,...,Yellow cards_away,Offsides_away,Offsides_home,Goalkeeper saves_away,Goalkeeper saves_home,team_h,team_a,date,h,a
0,81,6767929,2015-08,1,0,4,25,0.44,0.42,2,...,3.0,2.0,1.0,1.0,4.0,Manchester United,Tottenham,2015-08-08 15:45:00,89,82
1,82,6767928,2015-08,6,0,7,30,0.37,0.50,3,...,4.0,2.0,2.0,2.0,2.0,Bournemouth,Aston Villa,2015-08-08 18:00:00,73,71
2,83,6767936,2015-08,8,0,3,30,0.43,0.41,2,...,2.0,1.0,4.0,3.0,3.0,Everton,Watford,2015-08-08 18:00:00,72,90
3,84,6767932,2015-08,6,0,8,21,0.54,0.39,3,...,4.0,1.0,0.0,4.0,3.0,Leicester,Sunderland,2015-08-08 18:00:00,75,77
4,85,6767933,2015-08,1,0,9,23,0.51,0.56,4,...,0.0,2.0,4.0,4.0,4.0,Norwich,Crystal Palace,2015-08-08 18:00:00,79,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3415,22270,11352562,2024-05,2,10,3,11,0.55,0.50,4,...,4.0,1.0,3.0,4.0,2.0,Crystal Palace,Aston Villa,2024-05-19 15:00:00,78,71
3416,22271,11352565,2024-05,10,14,12,14,0.42,0.78,2,...,1.0,2.0,3.0,11.0,2.0,Liverpool,Wolverhampton Wanderers,2024-05-19 15:00:00,87,229
3417,22272,11352568,2024-05,4,15,4,12,0.47,0.65,4,...,4.0,1.0,8.0,4.0,4.0,Luton,Fulham,2024-05-19 15:00:00,256,228
3418,22273,11352571,2024-05,11,3,9,15,0.61,0.57,2,...,1.0,0.0,3.0,9.0,1.0,Manchester City,West Ham,2024-05-19 15:00:00,88,81
3419,22274,11352574,2024-05,2,11,3,19,0.47,0.45,6,...,0.0,0.0,6.0,1.0,6.0,Sheffield United,Tottenham,2024-05-19 15:00:00,238,82

In [142]:
df_to_save.columns

Index(['id', 'sofa_id', 'year_month', 'Corner kicks_home', 'Fouls_home',
       'Shots off target_home', 'Throw-ins_home', 'Ground duels_home',
       'Aerial duels_home', 'Corner kicks_away', 'Fouls_away',
       'Shots off target_away', 'Throw-ins_away',
       'Blocked per shots on target_home', 'Blocked per shots on target_away',
       'Shots on target per total shots_home',
       'Shots on target per total shots_away',
       'Hit woodwork per total shots_home',
       'Hit woodwork per total shots_away',
       'Shots outside box per total shots_home',
       'Shots outside box per total shots_away', 'Game dominance_home',
       'Game dominance_away', 'Overall game dominance', 'Big chances_home',
       'Big chances_away', 'Fouled in final third_away',
       'Fouled in final third_home', 'Long balls_away', 'Tackles won_home',
       'Crosses_away', 'Dribbles_away', 'Tackles won_away', 'Dribbles_home',
       'Crosses_home', 'Long balls_home', 'Yellow cards_home',
       'Yellow cards_away', 'Offsides_away', 'Offsides_home',
       'Goalkeeper saves_away', 'Goalkeeper saves_home', 'team_h', 'team_a',
       'date', 'h', 'a'],
      dtype='object')

In [143]:
import re
# Find columns that have _home or _away in their names
def pivot_dataframe(df):
    home_cols = [col for col in df.columns if re.search(r'_home$', col)]
    # Create home DataFrame and rename columns to their original names without _home suffix

    home_df = df[["id", "sofa_id", "h", "date"] + home_cols].copy()
    home_df.columns = [col.replace('_home', '') for col in home_df.columns]
    home_df.rename(columns={'h': 'team_id'}, inplace=True)
    home_df["h_a"]= "h"


    away_cols = [col for col in df.columns if re.search(r'_away$', col)]
    away_df = df[["id", "sofa_id", "a", "date"] + away_cols].copy()
    away_df.columns = [col.replace('_away', '') for col in away_df.columns]
    away_df.rename(columns={'a': 'team_id'}, inplace=True)
    away_df["h_a"]= "a"
    return pd.concat([home_df, away_df], ignore_index=True)
df_to_save_pivoted = pivot_dataframe(df_to_save)
df_to_save_pivoted

,id,sofa_id,team_id,date,Corner kicks,Fouls,Shots off target,Throw-ins,Ground duels,Aerial duels,...,Big chances,Fouled in final third,Tackles won,Dribbles,Crosses,Long balls,Yellow cards,Offsides,Goalkeeper saves,h_a
0,81,6767929,89,2015-08-08 15:45:00,1,0,4,25,0.44,0.42,...,1.0,0.0,1.00,0.00,0.00,0.00,2.0,1.0,4.0,h
1,82,6767928,73,2015-08-08 18:00:00,6,0,7,30,0.37,0.50,...,2.0,1.0,1.00,0.00,0.00,1.00,3.0,2.0,2.0,h
2,83,6767936,72,2015-08-08 18:00:00,8,0,3,30,0.43,0.41,...,3.0,1.0,1.00,0.00,0.00,1.00,1.0,4.0,3.0,h
3,84,6767932,75,2015-08-08 18:00:00,6,0,8,21,0.54,0.39,...,4.0,0.0,1.00,1.00,0.00,0.00,2.0,0.0,3.0,h
4,85,6767933,79,2015-08-08 18:00:00,1,0,9,23,0.51,0.56,...,2.0,1.0,1.00,1.00,0.00,1.00,1.0,4.0,4.0,h
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6835,22270,11352562,71,2024-05-19 15:00:00,4,8,6,17,NaN,NaN,...,2.0,1.0,0.20,0.56,0.30,0.47,4.0,1.0,4.0,a
6836,22271,11352565,229,2024-05-19 15:00:00,2,10,0,17,NaN,NaN,...,1.0,2.0,0.48,0.58,0.00,0.33,1.0,2.0,11.0,a
6837,22272,11352568,228,2024-05-19 15:00:00,4,20,6,15,NaN,NaN,...,2.0,4.0,0.45,0.45,0.33,0.52,4.0,1.0,4.0,a
6838,22273,11352571,81,2024-05-19 15:00:00,2,12,1,13,NaN,NaN,...,0.0,0.0,0.64,0.64,0.33,0.33,1.0,0.0,9.0,a
6839,22274,11352574,82,2024-05-19 15:00:00,6,9,3,24,NaN,NaN,...,3.0,1.0,0.75,0.30,0.13,0.71,0.0,0.0,1.0,a

In [144]:
df_to_save_pivoted.sort_values(by=['id'])

,id,sofa_id,team_id,date,Corner kicks,Fouls,Shots off target,Throw-ins,Ground duels,Aerial duels,...,Big chances,Fouled in final third,Tackles won,Dribbles,Crosses,Long balls,Yellow cards,Offsides,Goalkeeper saves,h_a
0,81,6767929,89,2015-08-08 15:45:00,1,0,4,25,0.44,0.42,...,1.0,0.0,1.00,0.00,0.00,0.00,2.0,1.0,4.0,h
3420,81,6767929,82,2015-08-08 15:45:00,2,0,2,24,NaN,NaN,...,3.0,0.0,1.00,1.00,0.00,0.00,3.0,2.0,1.0,a
3421,82,6767928,71,2015-08-08 18:00:00,3,0,2,19,NaN,NaN,...,2.0,0.0,1.00,1.00,0.00,0.00,4.0,2.0,2.0,a
1,82,6767928,73,2015-08-08 18:00:00,6,0,7,30,0.37,0.50,...,2.0,1.0,1.00,0.00,0.00,1.00,3.0,2.0,2.0,h
2,83,6767936,72,2015-08-08 18:00:00,8,0,3,30,0.43,0.41,...,3.0,1.0,1.00,0.00,0.00,1.00,1.0,4.0,3.0,h
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3067,22303,11352524,238,2023-08-27 13:00:00,1,11,4,11,0.38,0.33,...,1.0,0.0,0.64,0.46,0.67,0.52,4.0,1.0,7.0,h
6488,22304,11352515,87,2023-08-27 15:30:00,9,10,3,20,NaN,NaN,...,1.0,3.0,0.58,0.48,0.25,0.29,2.0,1.0,7.0,a
3068,22304,11352515,86,2023-08-27 15:30:00,5,16,11,13,0.51,0.53,...,1.0,2.0,0.63,0.67,0.46,0.46,1.0,0.0,2.0,h
6738,25861,11977248,256,2024-03-13 19:30:00,3,11,3,21,NaN,NaN,...,5.0,5.0,0.59,0.20,0.31,0.26,2.0,1.0,5.0,a
3318,25861,11977248,73,2024-03-13 19:30:00,11,16,6,28,0.56,0.49,...,4.0,1.0,0.71,0.67,0.22,0.41,1.0,1.0,1.0,h

In [145]:
df_to_save_pivoted[df_to_save_pivoted['id'] == 2686]

,id,sofa_id,team_id,date,Corner kicks,Fouls,Shots off target,Throw-ins,Ground duels,Aerial duels,...,Big chances,Fouled in final third,Tackles won,Dribbles,Crosses,Long balls,Yellow cards,Offsides,Goalkeeper saves,h_a
479,2686,7090118,85,2016-11-01 00:00:00,6,7,8,27,0.63,0.37,...,3.0,2.0,0.86,0.67,0.13,0.34,2.0,2.0,5.0,h
3899,2686,7090118,84,2016-11-01 00:00:00,4,14,4,24,NaN,NaN,...,1.0,1.0,0.79,0.50,0.47,0.47,0.0,1.0,2.0,a

In [146]:
df_to_save_pivoted[(df_to_save_pivoted['id'] == 2686) & (df_to_save_pivoted['h_a'] == 'h')]["Ground duels"].values[0]

0.63

In [147]:
id_list = df_to_save_pivoted['id'].unique().tolist()
for id in id_list:
    ground_duels= 1-(df_to_save_pivoted[(df_to_save_pivoted['id'] == id) & (df_to_save_pivoted['h_a'] == 'h')][["Ground duels"]].values[0])
    aerial_duels= 1-(df_to_save_pivoted[(df_to_save_pivoted['id'] == id) & (df_to_save_pivoted['h_a'] == 'h')][["Aerial duels"]].values[0])
    df_to_save_pivoted.loc[
        (df_to_save_pivoted['id'] == id) & (df_to_save_pivoted['h_a'] == 'a'), 
        "Ground duels"] = ground_duels
    df_to_save_pivoted.loc[
        (df_to_save_pivoted['id'] == id) & (df_to_save_pivoted['h_a'] == 'a'), 
        "Aerial duels"] = aerial_duels

In [148]:
df_to_save_pivoted.columns

Index(['id', 'sofa_id', 'team_id', 'date', 'Corner kicks', 'Fouls',
       'Shots off target', 'Throw-ins', 'Ground duels', 'Aerial duels',
       'Blocked per shots on target', 'Shots on target per total shots',
       'Hit woodwork per total shots', 'Shots outside box per total shots',
       'Game dominance', 'Big chances', 'Fouled in final third', 'Tackles won',
       'Dribbles', 'Crosses', 'Long balls', 'Yellow cards', 'Offsides',
       'Goalkeeper saves', 'h_a'],
      dtype='object')

In [149]:
df_to_save_pivoted.to_csv("Data/sofa_stats_with_understat_id.csv", index=False)