PLEASE REFER TO APPENDIX ON HOW TO RUN THE CODE, CHANGE THE FILE NAMES ACCORDINGLY IN ORDER FOR THE DATASETS TO BE IMPORTED ON YOUR SYSTEM. YOU CAN LOCATE THE WHEREABOUTS OF THE CSV'S BY CHECKING THE PATHWAY WHERE THE CODE IS TRYING TO IMPORT

USE localized_url function if there's an error with the imports

In [ ]:
import os
def localized_url(url):

    current_dir = os.getcwd().split("statistical-analysis-and-modeling-of-football-data")[0] + "statistical-analysis-and-modeling-of-football-data"
    branch = url.split("statistical-analysis-and-modeling-of-football-data")[1]
    return current_dir + branch

In [92]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import requests
import io
import tqdm

In [ ]:
understat_roster= pd.read_csv(localized_url('/Users/yarkin/Desktop/Dissertation/statistical-analysis-and-modeling-of-football-data/Understat/Data/understat_roster_1524.csv'))

In [94]:
understat_roster

,id,goals,own_goals,shots,xG,time,player_id,team_id,position,player,...,red_card,roster_in,roster_out,key_passes,assists,xA,xGChain,xGBuildup,positionOrder,match_link
0,620382,0,0,0,0.000000,90,560,89,GK,Sergio Romero,...,0,0,0,0,0,0.000000,0.000000,0.000000,1,https://understat.com/match/81
1,620383,0,0,0,0.000000,82,557,89,DR,Matteo Darmian,...,0,620393,0,1,0,0.106513,0.106513,0.106513,2,https://understat.com/match/81
2,620385,0,0,0,0.000000,90,628,89,DC,Chris Smalling,...,0,0,0,0,0,0.000000,0.106513,0.106513,3,https://understat.com/match/81
3,620384,0,0,0,0.000000,90,548,89,DC,Daley Blind,...,0,0,0,0,0,0.000000,0.127738,0.127738,3,https://understat.com/match/81
4,620386,0,0,0,0.000000,90,1006,89,DL,Luke Shaw,...,0,0,0,0,0,0.000000,0.021225,0.021225,4,https://understat.com/match/81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96086,663140,0,0,1,0.113749,9,7198,82,Sub,Oliver Skipp,...,0,0,663133,0,0,0.000000,0.113749,0.000000,17,https://understat.com/match/22274
96087,663138,0,0,0,0.000000,9,7430,82,Sub,Emerson,...,0,0,663128,0,0,0.000000,0.067532,0.067532,17,https://understat.com/match/22274
96088,663141,0,0,0,0.000000,1,9332,82,Sub,Dane Scarlett,...,0,0,663136,0,0,0.000000,0.000000,0.000000,17,https://understat.com/match/22274
96089,663139,0,0,1,0.046925,19,343,82,Sub,Pierre-Emile Højbjerg,...,0,0,663132,0,0,0.000000,0.901846,0.901846,17,https://understat.com/match/22274
96090,663142,0,0,0,0.000000,1,12603,82,Sub,Mikey Moore,...,0,0,663135,0,0,0.000000,0.000000,0.000000,17,https://understat.com/match/22274

In [ ]:
understat_matches= pd.read_csv(localized_url("/Users/yarkin/Desktop/Dissertation/statistical-analysis-and-modeling-of-football-data/Understat/Data/understat_epl1524_processed.csv"))

In [96]:
understat_matches

,id,fid,h,a,date,league_id,season,h_goals,a_goals,team_h,...,league,h_xg,a_xg,h_d,h_deep,a_deep,a_ppda,h_ppda,Shots on target per total shots_home,Shots on target per total shots_away
0,81,958431,89,82,2015-08-08 15:45:00,1,2015,1,0,Manchester United,...,EPL,0.627539,0.674600,0.3905,4,10,8.2188,13.8261,0.111111,0.444444
1,82,958427,73,71,2015-08-08 18:00:00,1,2015,0,1,Bournemouth,...,EPL,0.876106,0.782253,0.3607,11,2,11.8462,6.9000,0.181818,0.428571
2,83,958429,72,90,2015-08-08 18:00:00,1,2015,2,2,Everton,...,EPL,0.604226,0.557892,0.4337,5,4,17.1579,6.6500,0.500000,0.454545
3,84,958430,75,77,2015-08-08 18:00:00,1,2015,4,2,Leicester,...,EPL,2.568030,1.459460,0.2057,5,6,9.5556,10.8800,0.421053,0.454545
4,85,958433,79,78,2015-08-08 18:00:00,1,2015,1,3,Norwich,...,EPL,1.130760,2.109750,0.2159,5,10,10.6250,5.7368,0.352941,0.636364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3415,22270,1729426,78,71,2024-05-19 15:00:00,1,2023,5,0,Crystal Palace,...,EPL,2.231890,0.598846,0.1508,11,0,30.3000,14.4783,0.600000,0.250000
3416,22271,1729428,87,229,2024-05-19 15:00:00,1,2023,2,0,Liverpool,...,EPL,5.659370,0.731254,0.0057,22,1,16.6000,5.0968,0.388889,0.750000
3417,22272,1729431,256,228,2024-05-19 15:00:00,1,2023,2,4,Luton,...,EPL,2.067430,1.115980,0.2206,4,5,10.5000,13.8947,0.400000,0.466667
3418,22273,1729434,88,81,2024-05-19 15:00:00,1,2023,3,1,Manchester City,...,EPL,2.315040,0.240159,0.1018,16,0,63.0000,8.0000,0.428571,0.666667
3419,22274,1729437,238,82,2024-05-19 15:00:00,1,2023,0,3,Sheffield United,...,EPL,0.697312,3.196750,0.0617,2,14,4.9565,33.9231,0.166667,0.500000

In [97]:
#change datetime format to only date :YYYY-MM-DD
understat_matches['date_for_clubelo'] = pd.to_datetime(understat_matches['date'], format='%Y-%m-%d %H:%M:%S').dt.date

In [98]:
understat_matches['date_for_clubelo']

0       2015-08-08
1       2015-08-08
2       2015-08-08
3       2015-08-08
4       2015-08-08
           ...
3415    2024-05-19
3416    2024-05-19
3417    2024-05-19
3418    2024-05-19
3419    2024-05-19
Name: date_for_clubelo, Length: 3420, dtype: object

In [99]:
clubelo_sample = requests.get("http://api.clubelo.com/2015-08-08")
clubelo_sample_df = pd.read_csv(io.StringIO(clubelo_sample.text))

In [100]:
clubelo_sample_df[clubelo_sample_df["Club"]=="Liverpool"]["Elo"]

26    1752.828369
Name: Elo, dtype: float64

In [101]:
date_list = understat_matches['date_for_clubelo'].unique().tolist()

In [102]:
date_to_df = {}
for date in tqdm.tqdm(date_list, desc="Fetching ClubELO data")  :
    try:
        clubelo_request = requests.get(f"http://api.clubelo.com/{date}")
        if clubelo_request.status_code != 200:
            print(f"Failed to fetch data for {date}: {clubelo_request.status_code}")
            break
        clubelo_df = pd.read_csv(io.StringIO(clubelo_request.text))
        date_to_df[date] = clubelo_df
    except Exception as e:
        print(f"Error fetching data for {date}: {e}")

Fetching ClubELO data:   1%|          | 10/1032 [00:16<28:37,  1.68s/it]

KeyboardInterrupt:

In [ ]:
import datetime
date_to_df[datetime.date(2015, 8, 10)]

,Rank,Club,Country,Level,Elo,From,To
0,1.0,Barcelona,ESP,1,2087.821777,2015-08-07,2015-08-19
1,2.0,Real Madrid,ESP,1,2062.769531,2015-08-07,2015-08-19
2,3.0,Bayern,GER,1,1980.942139,2015-08-07,2015-08-14
3,4.0,Atletico,ESP,1,1945.589722,2015-08-07,2015-08-19
4,5.0,Juventus,ITA,1,1920.675293,2015-08-07,2015-08-18
...,...,...,...,...,...,...,...
620,NaN,Lusitanos,AND,0,775.068665,2015-07-10,2016-06-28
621,NaN,Matecosa Sant Julia,AND,0,772.519836,2015-07-10,2016-06-28
622,NaN,Juvenes,SMR,0,696.204407,2015-07-10,2016-06-28
623,NaN,Folgore,SMR,0,693.877380,2015-07-10,2016-06-28
624,NaN,La Fiorita,SMR,0,689.511292,2015-07-10,2016-06-28

In [ ]:
test_dict= {1: "a", 2: "b", 3: "c"}
test_dict.items()

dict_items([(1, 'a'), (2, 'b'), (3, 'c')])

In [ ]:
team_date_elo_df = pd.DataFrame()
for date, df in tqdm.tqdm(date_to_df.items()):
    df["date"] = date
    team_date_elo_df = pd.concat([team_date_elo_df, df], ignore_index=True)

100%|██████████| 1032/1032 [00:10<00:00, 99.30it/s]

In [ ]:
team_date_elo_df.to_csv("Data/clubelo_team_date_elo.csv", index=False)

In [ ]:
understat_matches = pd.merge(understat_matches, team_date_elo_df[['Club', 'date', 'Elo']], how='left', left_on=['team_h', 'date_for_clubelo'], right_on=['Club', 'date'])

In [ ]:
understat_matches

,id,fid,h,a,date_x,league_id,season,h_goals,a_goals,team_h,...,h_deep,a_deep,a_ppda,h_ppda,Shots on target per total shots_home,Shots on target per total shots_away,date_for_clubelo,Club,date_y,Elo
0,81,958431,89,82,2015-08-08 15:45:00,1,2015,1,0,Manchester United,...,4,10,8.2188,13.8261,0.111111,0.444444,2015-08-08,NaN,NaN,NaN
1,82,958427,73,71,2015-08-08 18:00:00,1,2015,0,1,Bournemouth,...,11,2,11.8462,6.9000,0.181818,0.428571,2015-08-08,Bournemouth,2015-08-08,1594.601929
2,83,958429,72,90,2015-08-08 18:00:00,1,2015,2,2,Everton,...,5,4,17.1579,6.6500,0.500000,0.454545,2015-08-08,Everton,2015-08-08,1706.561157
3,84,958430,75,77,2015-08-08 18:00:00,1,2015,4,2,Leicester,...,5,6,9.5556,10.8800,0.421053,0.454545,2015-08-08,Leicester,2015-08-08,1633.624390
4,85,958433,79,78,2015-08-08 18:00:00,1,2015,1,3,Norwich,...,5,10,10.6250,5.7368,0.352941,0.636364,2015-08-08,Norwich,2015-08-08,1615.207520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3415,22270,1729426,78,71,2024-05-19 15:00:00,1,2023,5,0,Crystal Palace,...,11,0,30.3000,14.4783,0.600000,0.250000,2024-05-19,Crystal Palace,2024-05-19,1742.572754
3416,22271,1729428,87,229,2024-05-19 15:00:00,1,2023,2,0,Liverpool,...,22,1,16.6000,5.0968,0.388889,0.750000,2024-05-19,Liverpool,2024-05-19,1897.344116
3417,22272,1729431,256,228,2024-05-19 15:00:00,1,2023,2,4,Luton,...,4,5,10.5000,13.8947,0.400000,0.466667,2024-05-19,Luton,2024-05-19,1572.353638
3418,22273,1729434,88,81,2024-05-19 15:00:00,1,2023,3,1,Manchester City,...,16,0,63.0000,8.0000,0.428571,0.666667,2024-05-19,NaN,NaN,NaN
3419,22274,1729437,238,82,2024-05-19 15:00:00,1,2023,0,3,Sheffield United,...,2,14,4.9565,33.9231,0.166667,0.500000,2024-05-19,Sheffield United,2024-05-19,1522.760010

In [ ]:
def nan_analysis(df):
    # Returns teams (team_h) with NaN values in Elo rating
    return df[df['Elo'].isna()]['team_h'].unique()

In [ ]:
nan_analysis(understat_matches)

array(['Manchester United', 'Newcastle United', 'West Bromwich Albion',
       'Manchester City', 'Wolverhampton Wanderers', 'Nottingham Forest'],
      dtype=object)

In [ ]:
team_date_elo_df[team_date_elo_df["Country"]=="ENG"]["Club"].unique()

array(['Chelsea', 'Manchester City', 'Arsenal', 'Manchester United',
       'Liverpool', 'Tottenham', 'Southampton', 'Everton', 'Stoke',
       'Swansea', 'Crystal Palace', 'West Bromwich Albion', 'Leicester',
       'Norwich', 'Sunderland', 'West Ham', 'Bournemouth',
       'Newcastle United', 'Aston Villa', 'Watford', 'Burnley', 'Hull',
       'Middlesbrough', 'QPR', 'Derby', 'Ipswich',
       'Wolverhampton Wanderers', 'Blackburn', 'Brentford', 'Cardiff',
       'Birmingham', 'Sheffield Weds', 'Charlton', 'Brighton',
       'Nottingham Forest', 'Bolton', 'Fulham', 'Leeds', 'Huddersfield',
       'Reading', 'Rotherham', 'Bristol City', 'MK Dons', 'Preston',
       'Burton', 'Wigan', 'Barnsley', 'Sheffield United', 'Millwall',
       'Luton', 'Coventry', 'Wycombe', 'Blackpool', 'Peterboro',
       'Plymouth'], dtype=object)

In [ ]:
understat_clubelo_clubnames_dict = {
    "Manchester City": "Man City",
    "Newcastle United": "Newcastle",
    "West Bromwich Albion": "West Brom",
    "Manchester United": "Man United",
    "Wolverhampton Wanderers": "Wolves",
    "Nottingham Forest": "Forest"
}

In [ ]:
understat_clubelo_clubnames_dict = {
    "Man City": "Manchester City",
    "Newcastle": "Newcastle United",
    "West Brom": "West Bromwich Albion",
    "Man United": "Manchester United",
    "Wolves": "Wolverhampton Wanderers",
    "Forest": "Nottingham Forest"
}

In [ ]:
# Change the club names in team_date_elo_df to match those in understat_matches
team_date_elo_df['Club'] = team_date_elo_df['Club'].replace(understat_clubelo_clubnames_dict)

In [ ]:
understat_matches = pd.merge(understat_matches, team_date_elo_df[['Club', 'date', 'Elo']], how='left', left_on=['team_h', 'date_for_clubelo'], right_on=['Club', 'date'])

In [ ]:
understat_matches

,id,fid,h,a,date_x,league_id,season,h_goals,a_goals,team_h,...,h_deep,a_deep,a_ppda,h_ppda,Shots on target per total shots_home,Shots on target per total shots_away,date_for_clubelo,Club,date_y,Elo
0,81,958431,89,82,2015-08-08 15:45:00,1,2015,1,0,Manchester United,...,4,10,8.2188,13.8261,0.111111,0.444444,2015-08-08,Manchester United,2015-08-08,1810.338257
1,82,958427,73,71,2015-08-08 18:00:00,1,2015,0,1,Bournemouth,...,11,2,11.8462,6.9000,0.181818,0.428571,2015-08-08,Bournemouth,2015-08-08,1594.601929
2,83,958429,72,90,2015-08-08 18:00:00,1,2015,2,2,Everton,...,5,4,17.1579,6.6500,0.500000,0.454545,2015-08-08,Everton,2015-08-08,1706.561157
3,84,958430,75,77,2015-08-08 18:00:00,1,2015,4,2,Leicester,...,5,6,9.5556,10.8800,0.421053,0.454545,2015-08-08,Leicester,2015-08-08,1633.624390
4,85,958433,79,78,2015-08-08 18:00:00,1,2015,1,3,Norwich,...,5,10,10.6250,5.7368,0.352941,0.636364,2015-08-08,Norwich,2015-08-08,1615.207520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3415,22270,1729426,78,71,2024-05-19 15:00:00,1,2023,5,0,Crystal Palace,...,11,0,30.3000,14.4783,0.600000,0.250000,2024-05-19,Crystal Palace,2024-05-19,1742.572754
3416,22271,1729428,87,229,2024-05-19 15:00:00,1,2023,2,0,Liverpool,...,22,1,16.6000,5.0968,0.388889,0.750000,2024-05-19,Liverpool,2024-05-19,1897.344116
3417,22272,1729431,256,228,2024-05-19 15:00:00,1,2023,2,4,Luton,...,4,5,10.5000,13.8947,0.400000,0.466667,2024-05-19,Luton,2024-05-19,1572.353638
3418,22273,1729434,88,81,2024-05-19 15:00:00,1,2023,3,1,Manchester City,...,16,0,63.0000,8.0000,0.428571,0.666667,2024-05-19,Manchester City,2024-05-19,2048.742920
3419,22274,1729437,238,82,2024-05-19 15:00:00,1,2023,0,3,Sheffield United,...,2,14,4.9565,33.9231,0.166667,0.500000,2024-05-19,Sheffield United,2024-05-19,1522.760010

In [ ]:
nan_analysis(understat_matches)

array([], dtype=object)

In [ ]:
understat_matches = pd.merge(understat_matches, team_date_elo_df[['Club', 'date', 'Elo']], how='left', left_on=['team_a', 'date_for_clubelo'], right_on=['Club', 'date'])

In [ ]:
understat_matches

,id,fid,h,a,date_x,league_id,season,h_goals,a_goals,team_h,...,h_ppda,Shots on target per total shots_home,Shots on target per total shots_away,date_for_clubelo,Club_x,date_y,Elo_x,Club_y,date,Elo_y
0,81,958431,89,82,2015-08-08 15:45:00,1,2015,1,0,Manchester United,...,13.8261,0.111111,0.444444,2015-08-08,Manchester United,2015-08-08,1810.338257,Tottenham,2015-08-08,1730.680176
1,82,958427,73,71,2015-08-08 18:00:00,1,2015,0,1,Bournemouth,...,6.9000,0.181818,0.428571,2015-08-08,Bournemouth,2015-08-08,1594.601929,Aston Villa,2015-08-08,1577.901123
2,83,958429,72,90,2015-08-08 18:00:00,1,2015,2,2,Everton,...,6.6500,0.500000,0.454545,2015-08-08,Everton,2015-08-08,1706.561157,Watford,2015-08-08,1574.087280
3,84,958430,75,77,2015-08-08 18:00:00,1,2015,4,2,Leicester,...,10.8800,0.421053,0.454545,2015-08-08,Leicester,2015-08-08,1633.624390,Sunderland,2015-08-08,1605.132446
4,85,958433,79,78,2015-08-08 18:00:00,1,2015,1,3,Norwich,...,5.7368,0.352941,0.636364,2015-08-08,Norwich,2015-08-08,1615.207520,Crystal Palace,2015-08-08,1646.781494
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3415,22270,1729426,78,71,2024-05-19 15:00:00,1,2023,5,0,Crystal Palace,...,14.4783,0.600000,0.250000,2024-05-19,Crystal Palace,2024-05-19,1742.572754,Aston Villa,2024-05-19,1787.570190
3416,22271,1729428,87,229,2024-05-19 15:00:00,1,2023,2,0,Liverpool,...,5.0968,0.388889,0.750000,2024-05-19,Liverpool,2024-05-19,1897.344116,Wolverhampton Wanderers,2024-05-19,1681.206665
3417,22272,1729431,256,228,2024-05-19 15:00:00,1,2023,2,4,Luton,...,13.8947,0.400000,0.466667,2024-05-19,Luton,2024-05-19,1572.353638,Fulham,2024-05-19,1707.895386
3418,22273,1729434,88,81,2024-05-19 15:00:00,1,2023,3,1,Manchester City,...,8.0000,0.428571,0.666667,2024-05-19,Manchester City,2024-05-19,2048.742920,West Ham,2024-05-19,1728.072998
3419,22274,1729437,238,82,2024-05-19 15:00:00,1,2023,0,3,Sheffield United,...,33.9231,0.166667,0.500000,2024-05-19,Sheffield United,2024-05-19,1522.760010,Tottenham,2024-05-19,1784.965820

In [ ]:
understat_matches.rename(columns={'Elo_x': 'Elo_team_h', 'Elo_y': 'Elo_team_a'}, inplace=True)

In [ ]:
understat_matches.columns

Index(['id', 'fid', 'h', 'a', 'date_x', 'league_id', 'season', 'h_goals',
       'a_goals', 'team_h', 'team_a', 'league', 'h_xg', 'a_xg', 'h_d',
       'h_deep', 'a_deep', 'a_ppda', 'h_ppda',
       'Shots on target per total shots_home',
       'Shots on target per total shots_away', 'date_for_clubelo', 'Club_x',
       'date_y', 'Elo_team_h', 'Club_y', 'date', 'Elo_team_a'],
      dtype='object')

In [ ]:
understat_matches.drop(columns=['Club_x', 'Club_y', 'date_y', 'date_x'], inplace=True)

In [91]:
team_date_elo_df.to_csv("clubelo_team_date_elo.csv", index=False)
understat_matches.to_csv("understat_matches_with_clubelo.csv", index=False)